# Generated by Django 4.2.16 on 2024-10-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_sale_price_alter_sale_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bag',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='legend',
            field=models.BooleanField(default=False),
        ),
    ]
